name: 🚀 CI Node Express

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.hotel-clic.com
          username: github@hotel-clic.com
          password: ${{ secrets.SNPASS_PASSWORD }}
          protocol: ftps
          timeout: 120000
          port: 21
          local-dir: api/
          server-dir: ./api.hotel-clic.com/